M48
; DRILL file {KiCad 7.0.5} date Fri Jul 21 14:17:59 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-07-21T14:17:59+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X2.888Y-1.7438
X2.9421Y-5.4938
X8.1608Y-1.7438
X8.1608Y-5.4938
T0
M30
